# Stage 0: generate reasoning steps without any latent thoughts yet
project: coconut
name: gsm-cot
save_path: exps/gsm8k_cot_cpu

only_eval: False

coconut: False
cot: True
no_thoughts: False
no_cot: False

c_thought: 0
epochs_per_stage: 1
max_latent_stage: 0
pad_latent_to_max: True

# CHANGE BACK TO TRUE
save_only_improve: False
uniform_prob: 0.0

model_id: openai-community/gpt2
# CHANGE BACK TO NONE
load_model_path: None

seed: 0
# CHANGE BACK TO 0
resume: 15
bf16: False
train_path: data/gsm_train.json
val_path: data/gsm_valid.json
reset_optimizer: False

# CHANGE BACK TO 16
batch_size_training: 8
debug: False
# CHANGE BACK TO 1
gradient_accumulation_steps: 2

num_epochs: 25
lr: 1.0e-4
# regularization term that penalizes large weights to prevent overfitting
weight_decay: 0.01
