# Stage 1+: Coconut (latent)
project: coconut
name: gsm-coconut
save_path: exps/gsm8k_coconut_cpu

only_eval: false

coconut: True
cot: False
no_thoughts: False
no_cot: False

c_thought: 2
epochs_per_stage: 3
max_latent_stage: 3
pad_latent_to_max: true

save_only_improve: false
uniform_prob: 0.0

model_id: openai-community/gpt2
load_model_path: exps/gsm8k_cot_cpu/best.pt  

seed: 0
resume: 3
bf16: false
train_path: data/gsm_train.json
val_path: data/gsm_valid.json
reset_optimizer: True

batch_size_training: 4
debug: true
gradient_accumulation_steps: 1

num_epochs: 10
lr: 1.0e-4
weight_decay: 0.01
